### ISSUE TITLE
Getting error message: "EROFS: read-only file system, open '/var/task/server/uploads/idImage-1691245247068.jpg'" in first step of generating ID card

### ISSUE THREAD

**Issue by devravimori** [itxSaaad/cardgenius-app-mern#1]
After registering I have tried to generate id card but it failed in first step of multi step of form saying that file is read only in file system, see below I have attached the screenshot:

![image](https://github.com/itxSaaad/cardgenius-app-mern/assets/96901635/ee9fbb2a-a4f8-4800-8185-01a90952a438)

In network the error message in json was like this:
```{message: "EROFS: read-only file system, open '/var/task/server/uploads/idImage-1691245247068.jpg'"}```

**Comment by itxSaaad** [comment]
Hey There!
Thanks For Reporting the issue, I've resolved the Issue Regarding Image Upload Now you can check the Site.
.
.
Don't Forget to Provide a Feedback and Star to the repo!
